all: output.txt

and.txt: input.txt
	sleep 1
	cat input.txt | grep and > and.txt

surrounded.txt: input.txt
	sleep 1
	cat input.txt | grep surrounded > surrounded.txt

often.txt: input.txt
	sleep 1
	cat input.txt | grep often > often.txt

blush.txt: input.txt
	sleep 1
	cat input.txt | grep blush > blush.txt

betrayed.txt: input.txt
	sleep 1
	cat input.txt | grep betrayed > betrayed.txt

related.txt: input.txt
	sleep 1
	cat input.txt | grep related > related.txt

an.txt: input.txt
	sleep 1
	cat input.txt | grep an > an.txt

winding.txt: input.txt
	sleep 1
	cat input.txt | grep winding > winding.txt

as.txt: input.txt
	sleep 1
	cat input.txt | grep as > as.txt

attended.txt: input.txt
	sleep 1
	cat input.txt | grep attended > attended.txt

at.txt: input.txt
	sleep 1
	cat input.txt | grep at > at.txt

another.txt: input.txt
	sleep 1
	cat input.txt | grep another > another.txt

in.txt: input.txt
	sleep 1
	cat input.txt | grep in > in.txt

fail.txt: input.txt
	sleep 1
	cat input.txt | grep fail > fail.txt

families.txt: input.txt
	sleep 1
	cat input.txt | grep families > families.txt

breakfast.txt: input.txt
	sleep 1
	cat input.txt | grep breakfast > breakfast.txt

yet.txt: input.txt
	sleep 1
	cat input.txt | grep yet > yet.txt

any.txt: input.txt
	sleep 1
	cat input.txt | grep any > any.txt

if.txt: input.txt
	sleep 1
	cat input.txt | grep if > if.txt

living.txt: input.txt
	sleep 1
	cat input.txt | grep living > living.txt

death.txt: input.txt
	sleep 1
	cat input.txt | grep death > death.txt

but.txt: input.txt
	sleep 1
	cat input.txt | grep but > but.txt

for.txt: input.txt
	sleep 1
	cat input.txt | grep for > for.txt

objection.txt: input.txt
	sleep 1
	cat input.txt | grep objection > objection.txt

convinced.txt: input.txt
	sleep 1
	cat input.txt | grep convinced > convinced.txt

since.txt: input.txt
	sleep 1
	cat input.txt | grep since > since.txt

gentleman.txt: input.txt
	sleep 1
	cat input.txt | grep gentleman > gentleman.txt

event.txt: input.txt
	sleep 1
	cat input.txt | grep event > event.txt

better.txt: input.txt
	sleep 1
	cat input.txt | grep better > better.txt

pure.txt: input.txt
	sleep 1
	cat input.txt | grep pure > pure.txt

new.txt: input.txt
	sleep 1
	cat input.txt | grep new > new.txt

inhabit.txt: input.txt
	sleep 1
	cat input.txt | grep inhabit > inhabit.txt

nay.txt: input.txt
	sleep 1
	cat input.txt | grep nay > nay.txt

is.txt: input.txt
	sleep 1
	cat input.txt | grep is > is.txt

daughters.txt: input.txt
	sleep 1
	cat input.txt | grep daughters > daughters.txt

improve.txt: input.txt
	sleep 1
	cat input.txt | grep improve > improve.txt

do.txt: input.txt
	sleep 1
	cat input.txt | grep do > do.txt

we.txt: input.txt
	sleep 1
	cat input.txt | grep we > we.txt

towards.txt: input.txt
	sleep 1
	cat input.txt | grep towards > towards.txt

led.txt: input.txt
	sleep 1
	cat input.txt | grep led > led.txt

terminated.txt: input.txt
	sleep 1
	cat input.txt | grep terminated > terminated.txt

downs.txt: input.txt
	sleep 1
	cat input.txt | grep downs > downs.txt

park.txt: input.txt
	sleep 1
	cat input.txt | grep park > park.txt

trees.txt: input.txt
	sleep 1
	cat input.txt | grep trees > trees.txt

met.txt: input.txt
	sleep 1
	cat input.txt | grep met > met.txt

finished.txt: input.txt
	sleep 1
	cat input.txt | grep finished > finished.txt

preferred.txt: input.txt
	sleep 1
	cat input.txt | grep preferred > preferred.txt

arranging.txt: input.txt
	sleep 1
	cat input.txt | grep arranging > arranging.txt

post.txt: input.txt
	sleep 1
	cat input.txt | grep post > post.txt

one.txt: input.txt
	sleep 1
	cat input.txt | grep one > one.txt

remainder.txt: input.txt
	sleep 1
	cat input.txt | grep remainder > remainder.txt

former.txt: input.txt
	sleep 1
	cat input.txt | grep former > former.txt

raising.txt: input.txt
	sleep 1
	cat input.txt | grep raising > raising.txt

he.txt: input.txt
	sleep 1
	cat input.txt | grep he > he.txt

case.txt: input.txt
	sleep 1
	cat input.txt | grep case > case.txt

on.txt: input.txt
	sleep 1
	cat input.txt | grep on > on.txt

expense.txt: input.txt
	sleep 1
	cat input.txt | grep expense > expense.txt

attempt.txt: input.txt
	sleep 1
	cat input.txt | grep attempt > attempt.txt

considered.txt: input.txt
	sleep 1
	cat input.txt | grep considered > considered.txt

of.txt: input.txt
	sleep 1
	cat input.txt | grep of > of.txt

bed.txt: input.txt
	sleep 1
	cat input.txt | grep bed > bed.txt

mrs.txt: input.txt
	sleep 1
	cat input.txt | grep mrs > mrs.txt

inhabiting.txt: input.txt
	sleep 1
	cat input.txt | grep inhabiting > inhabiting.txt

she.txt: input.txt
	sleep 1
	cat input.txt | grep she > she.txt

mr.txt: input.txt
	sleep 1
	cat input.txt | grep mr > mr.txt

the.txt: input.txt
	sleep 1
	cat input.txt | grep the > the.txt

contrasted.txt: input.txt
	sleep 1
	cat input.txt | grep contrasted > contrasted.txt

its.txt: input.txt
	sleep 1
	cat input.txt | grep its > its.txt

insensible.txt: input.txt
	sleep 1
	cat input.txt | grep insensible > insensible.txt

clothes.txt: input.txt
	sleep 1
	cat input.txt | grep clothes > clothes.txt

output.txt: and.txt surrounded.txt often.txt blush.txt betrayed.txt related.txt an.txt winding.txt as.txt attended.txt at.txt another.txt in.txt fail.txt families.txt breakfast.txt yet.txt any.txt if.txt living.txt death.txt but.txt for.txt objection.txt convinced.txt since.txt gentleman.txt event.txt better.txt pure.txt new.txt inhabit.txt nay.txt is.txt daughters.txt improve.txt do.txt we.txt towards.txt led.txt terminated.txt downs.txt park.txt trees.txt met.txt finished.txt preferred.txt arranging.txt post.txt one.txt remainder.txt former.txt raising.txt he.txt case.txt on.txt expense.txt attempt.txt considered.txt of.txt bed.txt mrs.txt inhabiting.txt she.txt mr.txt the.txt contrasted.txt its.txt insensible.txt clothes.txt
	sleep 1
	cat and.txt surrounded.txt often.txt blush.txt betrayed.txt related.txt an.txt winding.txt as.txt attended.txt at.txt another.txt in.txt fail.txt families.txt breakfast.txt yet.txt any.txt if.txt living.txt death.txt but.txt for.txt objection.txt convinced.txt since.txt gentleman.txt event.txt better.txt pure.txt new.txt inhabit.txt nay.txt is.txt daughters.txt improve.txt do.txt we.txt towards.txt led.txt terminated.txt downs.txt park.txt trees.txt met.txt finished.txt preferred.txt arranging.txt post.txt one.txt remainder.txt former.txt raising.txt he.txt case.txt on.txt expense.txt attempt.txt considered.txt of.txt bed.txt mrs.txt inhabiting.txt she.txt mr.txt the.txt contrasted.txt its.txt insensible.txt clothes.txt > output.txt
